package com.project.uber;

import com.project.uber.services.EmailSenderService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class UberApplicationTests {
	@Autowired
	private  EmailSenderService emailSenderService;

	@Test
	void contextLoads() {
		emailSenderService.sendEmail(
				"johaxi9823@codverts.com",
				"This is the test email",
				"This is the body of test email");
	}

	@Test
	void sendMultipleEmail(){
		String[] emails = {
				"vivekshinde1188@gmail.com",
				"vivek.shinde7588@gmail.com"
		};
		emailSenderService.sendEmail(
				emails,
				"Hello from Demo UBER applications",
				"This mail is generated by DEMO app"
		);
	}
}
